# Generated by Django 4.2 on 2023-04-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('M', 'Mouse'), ('B', 'Bird'), ('S', 'Strawberry')], default='M', max_length=1)),
                ('snek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.snek')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
