# Generated by Django 4.2 on 2023-04-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_snek_toys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snek',
            new_name='Snake',
        ),
    ]
