# Generated by Django 4.2 on 2023-04-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_snek_snake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='toys',
            field=models.ManyToManyField(blank=True, to='main_app.toy'),
        ),
    ]
